language: ruby
rvm:
  2.5.1

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --assume-extension --disable-external --url-ignore "#,#fn:1" --file-ignore "./_site/assets/snippet/profile.html" ./_site

branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
